"""updated register r1 fields

Revision ID: 12a65e762ed3
Revises: 207e6a07be0a
Create Date: 2026-04-29 13:53:29.296801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a65e762ed3'
down_revision = '207e6a07be0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_r1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('judgement_for_what', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('appeal_number_year', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('appeal_order_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('adjustment_particulars', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('serial_no_under_rule', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('execution_application_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('execution_against_whom', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('execution_for_what', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('costs_amount', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paid_into_court', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('relief_amount_due', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('person_detained', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('return_minute', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('appeal_revision_orders', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_r1', schema=None) as batch_op:
        batch_op.drop_column('appeal_revision_orders')
        batch_op.drop_column('return_minute')
        batch_op.drop_column('person_detained')
        batch_op.drop_column('relief_amount_due')
        batch_op.drop_column('paid_into_court')
        batch_op.drop_column('costs_amount')
        batch_op.drop_column('execution_for_what')
        batch_op.drop_column('execution_against_whom')
        batch_op.drop_column('execution_application_details')
        batch_op.drop_column('serial_no_under_rule')
        batch_op.drop_column('adjustment_particulars')
        batch_op.drop_column('appeal_order_details')
        batch_op.drop_column('appeal_number_year')
        batch_op.drop_column('judgement_for_what')

    # ### end Alembic commands ###
