"""register r1 table created

Revision ID: 207e6a07be0a
Revises: 
Create Date: 2026-04-29 09:21:47.624546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '207e6a07be0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desg_t',
    sa.Column('desgcode', sa.INTEGER(), nullable=False),
    sa.Column('desgname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('display', sa.VARCHAR(length=1), nullable=False),
    sa.Column('create_modify', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('desgcode'),
    schema='public'
    )
    op.create_table('judge_name_t',
    sa.Column('judge_code', sa.Integer(), nullable=False),
    sa.Column('judge_name', sa.String(length=100), nullable=False),
    sa.Column('display', sa.String(length=1), nullable=False),
    sa.Column('jto_dt', sa.Date(), nullable=True),
    sa.Column('jfrom_dt', sa.Date(), nullable=True),
    sa.Column('desg_code', sa.Integer(), nullable=True),
    sa.Column('jocode', sa.String(length=10), nullable=True),
    sa.Column('create_modify', sa.TIMESTAMP(), nullable=True),
    sa.Column('est_code_src', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('judge_code', 'est_code_src'),
    schema='public'
    )
    op.create_table('judge_t',
    sa.Column('court_no', sa.INTEGER(), nullable=False),
    sa.Column('judge_code', sa.INTEGER(), nullable=False),
    sa.Column('jocode', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desg_code', sa.INTEGER(), nullable=True),
    sa.Column('from_dt', sa.DATE(), nullable=False),
    sa.Column('to_dt', sa.DATE(), nullable=True),
    sa.Column('incharge', sa.CHAR(length=1), nullable=True),
    sa.Column('est_code_src', sa.VARCHAR(length=8), nullable=False),
    sa.Column('display', sa.CHAR(length=1), nullable=True),
    sa.Column('create_modify', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('court_no', 'judge_code', 'from_dt', 'est_code_src'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('judge_t', schema='public')
    op.drop_table('judge_name_t', schema='public')
    op.drop_table('desg_t', schema='public')
    # ### end Alembic commands ###
