"""create r20 table

Revision ID: cecaa95325c9
Revises: 12a65e762ed3
Create Date: 2026-04-30 10:04:40.402658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecaa95325c9'
down_revision = '12a65e762ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register_r20',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_name', sa.String(length=255), nullable=False),
    sa.Column('consecutive_no', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.Integer(), nullable=False),
    sa.Column('parties', sa.String(length=255), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('file_details', sa.String(length=100), nullable=True),
    sa.Column('disposed_date', sa.Date(), nullable=True),
    sa.Column('shelf_details', sa.String(length=250), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('register_r20')
    # ### end Alembic commands ###
