"""create r34 table

Revision ID: e4b757923dd5
Revises: cecaa95325c9
Create Date: 2026-05-05 09:22:57.613824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b757923dd5'
down_revision = 'cecaa95325c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_r34', schema=None) as batch_op:
        batch_op.alter_column('serial_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_r34', schema=None) as batch_op:
        batch_op.alter_column('serial_no',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
